# Generated by Django 5.0 on 2023-12-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True,
                                            upload_to='get_in_touch'
                                            '/bio_images')),
                ('last_update', models.DateField(auto_now_add=True,
                                                 null=True)),
            ],
        ),
    ]
