# Generated by Django 5.0 on 2024-02-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_in_touch', '0002_collaboraterequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='image',
            field=models.ImageField(blank=True, null=True,
                                    upload_to='get_in_touch/bio_images'),
        ),
    ]
