# Generated by Django 5.0 on 2024-02-11 18:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_in_touch', '0003_alter_bio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True, verbose_name='image'),
        ),
    ]
